apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cctv-viewer.fullname" . }}-config
  labels:
    {{- include "cctv-viewer.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
