apiVersion: v1
kind: Service
metadata:
  name: {{ include "cctv-viewer.fullname" . }}
  labels:
    {{- include "cctv-viewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portApi }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.portWeb }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "cctv-viewer.selectorLabels" . | nindent 4 }}
